### ISSUE TITLE
Trained model

### ISSUE THREAD

**Issue by Kyanite123** [lizhengwei1992/Semantic_Human_Matting#17]
Hi Li, 

Thank you so much for sharing your code! 

Is it possible for you to upload the already trained model? It would be great to have a reference before starting training by my own (I'm quite new at this).

Many thanks, 
K.

**Comment by dingdajun** [comment]
https://github.com/lizhengwei1992/Semantic_Human_Matting/tree/fast_human_matting

**Comment by dingdajun** [comment]
suggestion: check the closed issue first.

**Comment by wuzb19951013** [comment]
But how can I use this pretrained model? 
Every time when I try to run it, it will show me the error:
 'Upsample' object has no attribute 'name'
Have anyone resolved this problem?

the total errors like this:
C:\Users\vanessa\Anaconda3\envs\pytorch\lib\site-packages\torch\serialization.py:435: SourceChangeWarning: source code of class 'model.T_Net.RD_FPNnet' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
C:\Users\vanessa\Anaconda3\envs\pytorch\lib\site-packages\torch\serialization.py:435: SourceChangeWarning: source code of class 'torch.nn.modules.pooling.AvgPool2d' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches
= True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
C:\Users\vanessa\Anaconda3\envs\pytorch\lib\site-packages\torch\serialization.py:435: SourceChangeWarning: source code of class 'torch.nn.modules.container.Sequential' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
C:\Users\vanessa\Anaconda3\envs\pytorch\lib\site-packages\torch\serialization.py:435: SourceChangeWarning: source code of class 'torch.nn.modules.conv.Conv2d' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
C:\Users\vanessa\Anaconda3\envs\pytorch\lib\site-packages\torch\serialization.py:435: SourceChangeWarning: source code of class 'torch.nn.modules.batchnorm.BatchNorm2d' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
C:\Users\vanessa\Anaconda3\envs\pytorch\lib\site-packages\torch\serialization.py:435: SourceChangeWarning: source code of class 'torch.nn.modules.activation.PReLU' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
C:\Users\vanessa\Anaconda3\envs\pytorch\lib\site-packages\torch\serialization.py:435: SourceChangeWarning: source code of class 'model.T_Net.ResidualDenseBlock' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
C:\Users\vanessa\Anaconda3\envs\pytorch\lib\site-packages\torch\serialization.py:435: SourceChangeWarning: source code of class 'model.T_Net.DenseBlock' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and
use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
C:\Users\vanessa\Anaconda3\envs\pytorch\lib\site-packages\torch\serialization.py:435: SourceChangeWarning: source code of class 'model.T_Net.make_dense' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and
use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
C:\Users\vanessa\Anaconda3\envs\pytorch\lib\site-packages\torch\serialization.py:435: SourceChangeWarning: source code of class 'torch.nn.modules.activation.ReLU' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches =
True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
C:\Users\vanessa\Anaconda3\envs\pytorch\lib\site-packages\torch\serialization.py:435: SourceChangeWarning: source code of class 'torch.nn.modules.upsampling.Upsample' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
C:\Users\vanessa\Anaconda3\envs\pytorch\lib\site-packages\torch\serialization.py:435: SourceChangeWarning: source code of class 'torch.nn.modules.pooling.MaxPool2d' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches
= True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
Traceback (most recent call last):
  File "c:\Users\vanessa\.vscode\extensions\ms-python.python-2019.6.24221\pythonFiles\ptvsd_launcher.py", line 43, in <module>
    main(ptvsdArgs)
  File "c:\Users\vanessa\.vscode\extensions\ms-python.python-2019.6.24221\pythonFiles\lib\python\ptvsd\__main__.py", line 434, in main
    run()
  File "c:\Users\vanessa\.vscode\extensions\ms-python.python-2019.6.24221\pythonFiles\lib\python\ptvsd\__main__.py", line 312, in run_file
    runpy.run_path(target, run_name='__main__')
  File "C:\Users\vanessa\Anaconda3\envs\pytorch\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\vanessa\Anaconda3\envs\pytorch\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\vanessa\Anaconda3\envs\pytorch\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "g:\torch项目\fast_human_matting\Semantic_Human_Matting-fast_human_matting\test_camera.py", line 126, in <module>
    main(args)
  File "g:\torch项目\fast_human_matting\Semantic_Human_Matting-fast_human_matting\test_camera.py", line 122, in main
    camera_seg(args, myModel)
  File "g:\torch项目\fast_human_matting\Semantic_Human_Matting-fast_human_matting\test_camera.py", line 113, in camera_seg
    frame_seg = seg_process(args, frame, net)
  File "g:\torch项目\fast_human_matting\Semantic_Human_Matting-fast_human_matting\test_camera.py", line 73, in seg_process
    trimap, alpha = net(inputs)
  File "C:\Users\vanessa\Anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "g:\torch项目\fast_human_matting\Semantic_Human_Matting-fast_human_matting\model\network.py", line 36, in forward
    trimap = self.t_net(input)
  File "C:\Users\vanessa\Anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "g:\torch项目\fast_human_matting\Semantic_Human_Matting-fast_human_matting\model\T_Net.py", line 379, in forward
    p3 = self.up(heatmap) + self.stage3_down(s3)
  File "C:\Users\vanessa\Anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\vanessa\Anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\upsampling.py", line 129, in forward
    warnings.warn("nn.{} is deprecated. Use nn.functional.interpolate instead.".format(self.name))
  File "C:\Users\vanessa\Anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 535, in __getattr__
    type(self).__name__, name))
AttributeError: 'Upsample' object has no attribute 'name'

**Comment by FantasyJXF** [comment]
@wuzb19951013  I use pytorch 0.4.0, the test demo works alright

**Comment by wuzb19951013** [comment]
@FantasyJXF I used pytorch 1.0.0. so Maybe it happens due to the difference between 0.4.0 and 1.0.0?
by the way, the master branch works well on pytorch 1.0.0. 
Thank you very much

**Comment by wuzb19951013** [comment]
yeah，you're right, the format of .pth file probably changed. Orz

**Comment by Jason-xin** [comment]
@dingdajun @FantasyJXF 
When I run ./test_camera.sh (--without_gpu), this error occurred:
AttributeError: Can't get attribute 'RD_FPNnet' on <module 'model.T_Net' from '/Users/jasonxin/Documents/dlworkspace/Semantic_Human_Matting/model/T_Net.py'>
My torch version is 1.0.0.

**Comment by FUNGERN** [comment]
@dingdajun @FantasyJXF How is your test result

**Comment by dganguly1120** [comment]
```'AvgPool2d' object has no attribute 'divisor_override'``` getting this error
Update: For Solution go through this https://github.com/lizhengwei1992/Semantic_Human_Matting/issues/24

**Comment by watertianyi** [comment]
@Jason-xin 
Did you solve it, this happened to me too
